// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public class PanelNames {
    
    public static string MenuPanel {
        get {
            return "MenuPanel";
        }
    }
    
    public static string SettingPanel {
        get {
            return "SettingPanel";
        }
    }
    
    public static string PlayingPanel {
        get {
            return "PlayingPanel";
        }
    }
    
    public static string RecordPanel {
        get {
            return "RecordPanel";
        }
    }
}
